### ISSUE TITLE
API Documentation Link goes to wrong product

### ISSUE THREAD

**Issue by ij0n** [adafruit/Adafruit_CircuitPython_VL53L1X#4]
On the main readme of this repository, the part:

"Documentation
API documentation for this library can be found on [Read the Docs](https://docs.circuitpython.org/projects/neopixel/en/latest/)."

is pointing to a neopixel library, but not to the documentation of the API of this chip.

**Comment by FoamyGuy** [comment]
Thanks for reporting. are you interested in submitting a PR to change it?

**Comment by ij0n** [comment]
No, because I dont know where this link should point to. But I would like to know, which is why I opened this issue.

**Comment by FoamyGuy** [comment]
@ij0n https://docs.circuitpython.org/projects/vl53l1x/en/latest/

**Comment by FoamyGuy** [comment]
resolved by #5
